#
# version.cmake : version du projet
#

set (QT_UTIL_MAJOR_VERSION "5")
set (QT_UTIL_MINOR_VERSION "7")
set (QT_UTIL_RELEASE_VERSION "8")
set (QT_UTIL_VERSION ${QT_UTIL_MAJOR_VERSION}.${QT_UTIL_MINOR_VERSION}.${QT_UTIL_RELEASE_VERSION})


